import { appPath } from "./paths";

export function ConstructiveLanding() {
  return <main className="lh-site">
    <header className="lh-nav">
      <a className="lh-brand" href="#top"><span className="lh-brand-mark">AS</span><span><strong>ASmeT</strong><small>CONSTRUCTIVE / CONTROL</small></span></a>
      <nav className="lh-nav-links"><a href="#about">О продукте</a><a href="#workflow">Как работает</a><a href={appPath("/login")}>Войти</a><a className="lh-nav-cta" href={appPath("/login")}>Открыть кабинет</a></nav>
    </header>
    <section className="lh-hero" id="top">
      <div className="lh-hero-copy"><p className="lh-eyebrow">CONSTRUCTIVE / ASmeT <span>LIVE</span></p><h1>Строительство<br /><em>под контролем.</em></h1><p className="lh-hero-lead">Constructive собирает объекты, команду, склады и подтверждённые строки работ в одной рабочей области.</p><div className="lh-hero-actions"><a className="lh-button lh-button-primary" href={appPath("/login")}>Открыть рабочее пространство</a><a className="lh-text-link" href="#workflow">Как это работает <span>↓</span></a></div><div className="lh-offer-line"><span>Данные вашей организации</span><i /><span>Ролевой доступ</span><i /><span>ASmeT в рабочем потоке</span></div></div>
      <div className="lh-hero-aside"><span className="lh-aside-index">01 / WORKSPACE</span><div className="lh-scan-line" /><strong>ОБЪЕКТЫ<br /><b>КОМАНДА</b></strong><strong>МАТЕРИАЛЫ<br /><b>ЖУРНАЛ</b></strong><small>Одна область для Creator и Master с доступом только к назначенным данным.</small></div>
    </section>
    <section className="lh-statement" id="about"><p className="lh-eyebrow">НЕ ТАБЛИЦА · РАБОЧАЯ ОБЛАСТЬ</p><h2>Видеть, что происходит.<br /><span>Понимать, что подтверждено.</span></h2><div className="lh-statement-foot"><p>Constructive помогает держать исполнение в поле зрения: от объекта и сотрудников до строк журнала и запросов ASmeT.</p><a className="lh-button lh-button-dark" href={appPath("/login")}>Перейти к данным</a></div></section>
    <section className="lh-process" id="workflow"><div className="lh-section-intro"><p className="lh-eyebrow">РАБОЧИЙ ЦИКЛ</p><h2>Порядок там, где раньше были разрозненные сообщения.</h2></div><div className="lh-process-list"><div className="lh-process-step"><span className="lh-step-number">01</span><div><h3>Назначьте область</h3><p>Creator открывает организацию и выдаёт ролевой доступ участникам команды.</p></div><span className="lh-step-arrow">↗</span></div><div className="lh-process-step"><span className="lh-step-number">02</span><div><h3>Соберите факты</h3><p>Объекты, сотрудники, склады и ставки видны в едином кабинете без лишнего доступа.</p></div><span className="lh-step-arrow">↗</span></div><div className="lh-process-step"><span className="lh-step-number">03</span><div><h3>Подтвердите работу</h3><p>ASmeT принимает сообщения, выделяет строки работ и сохраняет историю с причинами отклонений.</p></div><span className="lh-step-arrow">↗</span></div></div></section>
    <section className="lh-pilot"><div><p className="lh-eyebrow">CONSTRUCTIVE / ДОСТУП</p><h2>Рабочая область<br /><em>готова к входу.</em></h2><p>После авторизации откроется только назначенная вам организация и доступные разделы кабинета.</p></div><div className="lh-pilot-offer"><span>Объекты · команда · склады · журнал · ASmeT</span><a className="lh-button lh-button-primary" href={appPath("/login")}>Войти в Constructive</a></div></section>
    <footer className="lh-footer"><a className="lh-brand" href="#top"><span className="lh-brand-mark">AS</span><span><strong>ASmeT</strong><small>CONSTRUCTIVE</small></span></a><p>Constructive управляет исполнением.<br />Доступ определяется ролью и организацией.</p><a className="lh-footer-login" href={appPath("/login")}>Войти в кабинет</a></footer>
  </main>;
}
