"""Add Stage 4 customer product boundary."""

import sqlalchemy as sa
from alembic import op

revision = "0014_stage4_customer_product"
down_revision = "0013_lead_analysis_rec_text"
branch_labels = None
depends_on = None


def _id():
    return sa.Column("id", sa.String(length=36), primary_key=True)


def _timestamps():
    return [sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False)]


def upgrade() -> None:
    op.create_table("product_organizations", _id(), *_timestamps(), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("workspaces.id"), nullable=False, unique=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="ACTIVE"))
    op.create_table("product_companies", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("website", sa.String(500)), sa.Column("social_url", sa.String(500)), sa.Column("description", sa.Text(), nullable=False), sa.Column("country", sa.String(80), nullable=False), sa.Column("region", sa.String(160)), sa.Column("customer_demand", sa.Text(), nullable=False), sa.Column("business_model", sa.JSON()), sa.Column("trial_used_at", sa.DateTime()), sa.Column("trial_campaign_id", sa.String(36)), sa.Column("status", sa.String(32), nullable=False, server_default="ACTIVE"))
    op.create_table("product_campaigns", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("company_id", sa.String(36), sa.ForeignKey("product_companies.id"), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("commercial_task", sa.Text(), nullable=False), sa.Column("geography", sa.String(200), nullable=False), sa.Column("minimum_value", sa.Float()), sa.Column("model_summary", sa.JSON(), nullable=False), sa.Column("model_version", sa.String(120), nullable=False, server_default="stage3-v1"), sa.Column("policy_status", sa.String(40), nullable=False, server_default="ALLOWED"), sa.Column("status", sa.String(32), nullable=False, server_default="DRAFT"), sa.Column("feedback", sa.JSON()), sa.UniqueConstraint("company_id", "commercial_task"))
    op.create_table("product_team_members", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("company_id", sa.String(36), sa.ForeignKey("product_companies.id"), nullable=False), sa.Column("campaign_id", sa.String(36), sa.ForeignKey("product_campaigns.id"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("role", sa.String(32), nullable=False, server_default="MEMBER"), sa.Column("status", sa.String(32), nullable=False, server_default="ACTIVE"), sa.UniqueConstraint("organization_id", "user_id", "campaign_id"))
    op.create_table("product_team_invitations", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("company_id", sa.String(36), sa.ForeignKey("product_companies.id"), nullable=False), sa.Column("campaign_id", sa.String(36), sa.ForeignKey("product_campaigns.id"), nullable=False), sa.Column("email", sa.String(255), nullable=False), sa.Column("role", sa.String(32), nullable=False, server_default="MEMBER"), sa.Column("token_hash", sa.String(128), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(), nullable=False), sa.Column("accepted_at", sa.DateTime()))
    op.create_table("product_payments", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("campaign_id", sa.String(36), sa.ForeignKey("product_campaigns.id"), nullable=False), sa.Column("amount", sa.Float(), nullable=False), sa.Column("currency", sa.String(8), nullable=False, server_default="RUB"), sa.Column("plan_code", sa.String(40), nullable=False), sa.Column("provider", sa.String(40), nullable=False, server_default="MANUAL_PAYMENT"), sa.Column("state", sa.String(32), nullable=False, server_default="PENDING"), sa.Column("external_reference", sa.String(200)), sa.Column("confirmed_at", sa.DateTime()))
    op.create_table("product_billing_agreements", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("campaign_id", sa.String(36), sa.ForeignKey("product_campaigns.id"), nullable=False), sa.Column("payment_id", sa.String(36), sa.ForeignKey("product_payments.id"), nullable=False), sa.Column("contract_type", sa.String(40), nullable=False, server_default="FIXED"), sa.Column("commercial_class", sa.String(32), nullable=False, server_default="STANDARD"), sa.Column("accepted_at", sa.DateTime(), nullable=False))
    op.create_table("product_entitlements", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("company_id", sa.String(36), sa.ForeignKey("product_companies.id"), nullable=False), sa.Column("campaign_id", sa.String(36), sa.ForeignKey("product_campaigns.id"), nullable=False), sa.Column("billing_agreement_id", sa.String(36), sa.ForeignKey("product_billing_agreements.id"), nullable=False), sa.Column("starts_at", sa.DateTime(), nullable=False), sa.Column("expires_at", sa.DateTime(), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="ACTIVE"), sa.Column("plan_code", sa.String(40), nullable=False), sa.Column("amount_paid", sa.Float(), nullable=False))
    op.create_table("product_promotions", _id(), *_timestamps(), sa.Column("code", sa.String(80), nullable=False, unique=True), sa.Column("kind", sa.String(32), nullable=False), sa.Column("value", sa.Float(), nullable=False, server_default="0"), sa.Column("free_days", sa.Integer(), nullable=False, server_default="0"), sa.Column("expires_at", sa.DateTime(), nullable=False), sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.CheckConstraint("free_days >= 0 AND free_days <= 30", name="ck_product_promotions_free_days"))
    op.create_table("product_founder_overrides", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("campaign_id", sa.String(36), sa.ForeignKey("product_campaigns.id"), nullable=False), sa.Column("granted_by", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("custom_price", sa.Float()), sa.Column("discount_percent", sa.Float()), sa.Column("free_days", sa.Integer(), nullable=False, server_default="0"), sa.Column("special_duration_days", sa.Integer()), sa.Column("commercial_class", sa.String(32)), sa.Column("starts_at", sa.DateTime(), nullable=False), sa.Column("expires_at", sa.DateTime(), nullable=False), sa.CheckConstraint("free_days >= 0 AND free_days <= 30", name="ck_product_founder_free_days"))
    op.create_table("product_opportunities", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("company_id", sa.String(36), sa.ForeignKey("product_companies.id"), nullable=False), sa.Column("campaign_id", sa.String(36), sa.ForeignKey("product_campaigns.id"), nullable=False), sa.Column("dedupe_key", sa.String(200), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("summary", sa.Text(), nullable=False), sa.Column("need", sa.Text(), nullable=False), sa.Column("location", sa.String(200)), sa.Column("budget", sa.String(160)), sa.Column("appeared_at", sa.DateTime(), nullable=False), sa.Column("source_url", sa.String(800)), sa.Column("why_matches", sa.Text(), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="NEW"), sa.Column("feedback_reason", sa.String(80)), sa.Column("acted_by", sa.String(36), sa.ForeignKey("users.id")), sa.Column("acted_at", sa.DateTime()), sa.UniqueConstraint("campaign_id", "dedupe_key"))
    op.create_table("product_notifications", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("campaign_id", sa.String(36), sa.ForeignKey("product_campaigns.id"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("kind", sa.String(32), nullable=False, server_default="IN_APP"), sa.Column("title", sa.String(200), nullable=False), sa.Column("body", sa.Text(), nullable=False), sa.Column("read_at", sa.DateTime()))
    op.create_table("product_audit_events", _id(), *_timestamps(), sa.Column("organization_id", sa.String(36), sa.ForeignKey("product_organizations.id"), nullable=False), sa.Column("actor_id", sa.String(36), sa.ForeignKey("users.id")), sa.Column("action", sa.String(100), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(36), nullable=False), sa.Column("details", sa.JSON()))


def downgrade() -> None:
    for name in ("product_audit_events", "product_notifications", "product_opportunities", "product_founder_overrides", "product_promotions", "product_entitlements", "product_billing_agreements", "product_payments", "product_team_invitations", "product_team_members", "product_campaigns", "product_companies", "product_organizations"):
        op.drop_table(name)
